# Comprehensive Traffic Congestion Reasons Database
# This file contains 500+ categorized congestion reasons for AI-based classification

CONGESTION_REASONS = {
    # ============================================================
    # CATEGORY 1: VEHICLE FLOW ISSUES (100 reasons)
    # ============================================================
    "vehicle_flow": [
        "normal traffic flow",
        "heavy traffic volume",
        "vehicles moving slowly",
        "vehicles stopped",
        "slow moving traffic due to high density",
        "traffic crawling at snail pace",
        "bumper to bumper traffic",
        "stop and go traffic pattern",
        "intermittent traffic flow",
        "reduced lane capacity causing slowdown",
        "traffic bottleneck ahead",
        "merging traffic causing delays",
        "lane reduction causing congestion",
        "traffic weaving between lanes",
        "vehicles changing lanes frequently",
        "aggressive driving causing slowdowns",
        "tailgating causing chain reaction braking",
        "traffic compression due to speed variance",
        "flow breakdown at bottleneck",
        "capacity drop due to high demand",
        "traffic demand exceeding capacity",
        "oversaturated intersection",
        "queue spillback from downstream",
        "traffic spillover from adjacent roads",
        "incoming traffic from side street",
        "traffic surge during peak hours",
        "morning rush hour congestion",
        "evening rush hour congestion",
        "lunchtime traffic surge",
        "school pickup time congestion",
        "office closing time traffic",
        "factory shift change traffic",
        "shopping mall traffic overflow",
        "stadium event traffic",
        "concert venue traffic surge",
        "festival crowd traffic",
        "religious gathering traffic",
        "market day traffic increase",
        "weekend leisure traffic",
        "holiday traffic congestion",
        "tourist season heavy traffic",
        "beach traffic during summer",
        "ski resort traffic in winter",
        "airport traffic during holidays",
        "train station congestion",
        "bus terminal traffic buildup",
        "metro station area congestion",
        "taxi stand queue overflow",
        "rideshare pickup zone congestion",
        "delivery vehicle clustering",
        "commercial vehicle traffic",
        "truck convoy passing through",
        "oversized vehicle causing slowdown",
        "wide load transport blocking lane",
        "military convoy passing",
        "funeral procession blocking traffic",
        "wedding procession",
        "VIP motorcade",
        "political rally traffic",
        "protest march blocking road",
        "parade causing road closure",
        "marathon event road block",
        "cycling event traffic diversion",
        "car show traffic overflow",
        "food truck festival traffic",
        "farmers market congestion",
        "night market traffic",
        "flea market crowd",
        "auction house traffic",
        "hospital visiting hours traffic",
        "clinic rush hour",
        "pharmacy queue overflow",
        "grocery store peak traffic",
        "supermarket weekend rush",
        "department store sale traffic",
        "black friday shopping traffic",
        "boxing day sale congestion",
        "new year sale traffic",
        "back to school shopping traffic",
        "graduation ceremony traffic",
        "university orientation traffic",
        "exam period traffic",
        "job fair traffic increase",
        "career expo congestion",
        "trade show traffic",
        "convention center traffic",
        "exhibition hall traffic surge",
        "art gallery opening traffic",
        "museum special event traffic",
        "theater performance traffic",
        "cinema premiere traffic",
        "restaurant district dinner rush",
        "bar area night traffic",
        "club district late night traffic",
        "casino traffic",
        "theme park traffic",
        "zoo weekend traffic",
        "aquarium holiday traffic",
        "botanical garden traffic",
        "park entrance congestion",
    ],
    
    # ============================================================
    # CATEGORY 2: PARKING & STOPPING ISSUES (80 reasons)
    # ============================================================
    "parking_issues": [
        "wrong parking blocking lane",
        "illegal parking on main road",
        "double parking causing obstruction",
        "triple parking blocking traffic",
        "parallel parking attempt blocking lane",
        "failed parking maneuver",
        "vehicle stuck while parking",
        "reversed parking blocking traffic",
        "parking lot overflow onto street",
        "parking garage queue extending to road",
        "valet parking blocking lane",
        "self parking vehicle malfunction",
        "parking meter expired vehicle blocking",
        "abandoned vehicle in lane",
        "vehicle left in traffic lane",
        "unattended vehicle causing obstruction",
        "delivery truck parked illegally",
        "moving truck blocking lane",
        "garbage truck stopped in lane",
        "mail truck frequent stops",
        "courier vehicle double parked",
        "food delivery vehicle stopped",
        "rideshare pickup blocking lane",
        "taxi waiting in traffic lane",
        "bus stopped outside designated area",
        "school bus loading zone overflow",
        "tour bus parking on street",
        "coach parking blocking traffic",
        "emergency vehicle parked on road",
        "police vehicle blocking lane",
        "ambulance stopped on road",
        "fire truck access blocking",
        "tow truck operation blocking lane",
        "roadside assistance blocking traffic",
        "vehicle breakdown in lane",
        "stalled vehicle blocking road",
        "overheated vehicle stopped",
        "flat tire change in lane",
        "engine failure stopped in traffic",
        "fuel empty vehicle blocking",
        "battery dead vehicle stuck",
        "transmission failure blocking",
        "brake failure stopped vehicle",
        "steering failure halted vehicle",
        "electrical failure stopped car",
        "mechanical failure causing obstruction",
        "vehicle ran out of windshield fluid",
        "wiper failure in rain blocking",
        "headlight failure at night",
        "vehicle inspection by authorities",
        "police checkpoint stopped vehicles",
        "immigration checkpoint queue",
        "customs inspection delay",
        "security checkpoint congestion",
        "DUI checkpoint traffic",
        "speed trap causing slowdown",
        "radar zone causing speed reduction",
        "camera zone speed reduction",
        "toll booth queue",
        "toll plaza congestion",
        "electronic toll collection failure",
        "cash lane toll queue",
        "border crossing delay",
        "bridge toll congestion",
        "tunnel entrance queue",
        "ferry terminal queue",
        "weighbridge queue for trucks",
        "loading zone blocked",
        "unloading zone congested",
        "drop off zone crowded",
        "pickup zone overwhelmed",
        "kiss and ride zone full",
        "carpool lane violation blocking",
        "bus lane obstruction",
        "bike lane parking violation",
        "crosswalk blocking",
        "intersection blocking",
        "yellow box junction blocking",
        "no stopping zone violation",
        "fire lane parking violation",
    ],
    
    # ============================================================
    # CATEGORY 3: TRAFFIC SIGNALS & INFRASTRUCTURE (70 reasons)
    # ============================================================
    "signal_infrastructure": [
        "traffic signal not working",
        "traffic light malfunction",
        "signal stuck on red",
        "signal stuck on green causing cross traffic",
        "all lights blinking yellow",
        "all lights blinking red",
        "traffic light completely dark",
        "incorrect signal timing",
        "poorly timed traffic lights",
        "signal phase too short",
        "pedestrian phase too long",
        "left turn signal too brief",
        "no protected left turn",
        "unprotected intersection",
        "missing traffic signal",
        "temporary signal causing confusion",
        "portable signal malfunction",
        "railroad crossing signal stuck",
        "school zone signal active",
        "construction zone signal confusion",
        "detour signal not clear",
        "one lane alternating signal",
        "flagman controlling traffic",
        "manual traffic control",
        "police directing traffic",
        "traffic controller absent",
        "smart signal system failure",
        "adaptive signal malfunction",
        "connected signal network down",
        "traffic sensor not detecting vehicles",
        "induction loop failure",
        "camera detection not working",
        "pedestrian button not responding",
        "crosswalk signal broken",
        "walk sign not illuminated",
        "countdown timer malfunction",
        "audible signal not working",
        "tactile signal failure",
        "sign obscured by vegetation",
        "sign blocked by truck",
        "sign vandalized",
        "sign missing",
        "confusing signage",
        "contradictory signs",
        "temporary signs confusing drivers",
        "detour signs missing",
        "lane marking faded",
        "road marking confusing",
        "arrow markings unclear",
        "stop line not visible",
        "crosswalk markings faded",
        "zebra crossing not visible",
        "speed bump unmarked",
        "pothole causing slowdown",
        "road depression causing caution",
        "uneven road surface",
        "bridge joint causing bump",
        "expansion joint damage",
        "road crack causing caution",
        "road buckling",
        "pavement failure",
        "sinkhole developing",
        "road subsidence",
        "road heave",
        "frost heave damage",
        "drainage grate dangerous",
        "manhole cover missing",
        "utility cover uneven",
        "curb damage",
        "guardrail damage",
    ],
    
    # ============================================================
    # CATEGORY 4: ACCIDENTS & INCIDENTS (80 reasons)
    # ============================================================
    "accidents_incidents": [
        "possible accident",
        "vehicle collision ahead",
        "rear end collision",
        "head on collision",
        "side swipe accident",
        "t-bone collision at intersection",
        "multi vehicle pileup",
        "chain reaction crash",
        "single vehicle accident",
        "vehicle hit guardrail",
        "vehicle went off road",
        "vehicle in ditch",
        "rollover accident",
        "vehicle flipped over",
        "vehicle hit median",
        "vehicle hit divider",
        "vehicle hit barrier",
        "vehicle hit pole",
        "vehicle hit sign post",
        "vehicle hit tree",
        "vehicle hit building",
        "vehicle hit pedestrian",
        "vehicle hit cyclist",
        "vehicle hit motorcyclist",
        "vehicle hit animal",
        "deer collision",
        "cattle on road collision",
        "dog on road incident",
        "bird strike on windshield",
        "hit and run accident",
        "lane departure crash",
        "wrong way driver collision",
        "drunk driving accident",
        "distracted driving crash",
        "texting while driving accident",
        "drowsy driving incident",
        "road rage incident",
        "aggressive driving crash",
        "speeding accident",
        "racing accident",
        "drag racing crash",
        "street racing incident",
        "motorcycle accident",
        "scooter accident",
        "bicycle accident",
        "e-bike crash",
        "e-scooter incident",
        "pedestrian accident",
        "jaywalking incident",
        "crosswalk accident",
        "child run accident",
        "elderly pedestrian incident",
        "wheelchair user accident",
        "stroller incident",
        "shopping cart incident",
        "skateboard accident",
        "roller skate incident",
        "vehicle fire",
        "engine fire",
        "tire fire",
        "cargo fire",
        "fuel leak fire",
        "electrical fire in vehicle",
        "bus fire",
        "truck fire",
        "hazmat spill",
        "chemical leak",
        "fuel spill on road",
        "oil spill making road slippery",
        "cargo spill blocking road",
        "grain spill on road",
        "gravel spill",
        "sand spill causing hazard",
        "glass debris on road",
        "metal debris on road",
        "tire debris blocking lane",
        "accident investigation blocking road",
        "police investigating scene",
        "forensic team on scene",
        "coroner on scene",
    ],
    
    # ============================================================
    # CATEGORY 5: ROAD WORK & CONSTRUCTION (60 reasons)
    # ============================================================
    "construction_roadwork": [
        "road blocked by construction",
        "lane closed for construction",
        "road resurfacing work",
        "asphalt laying operation",
        "concrete pouring blocking road",
        "road widening project",
        "bridge construction",
        "overpass construction",
        "underpass construction",
        "tunnel construction",
        "flyover construction",
        "interchange construction",
        "roundabout construction",
        "intersection reconfiguration",
        "median construction",
        "pedestrian bridge construction",
        "cycling path construction",
        "bus stop construction",
        "railway crossing upgrade",
        "level crossing work",
        "grade separation work",
        "culvert construction",
        "storm drain installation",
        "sewer line work",
        "water main repair",
        "water main break repair",
        "gas line installation",
        "gas leak repair",
        "electrical cable laying",
        "fiber optic installation",
        "telecommunications work",
        "utility pole installation",
        "streetlight installation",
        "traffic signal installation",
        "sign installation work",
        "guardrail installation",
        "barrier installation",
        "curb installation",
        "sidewalk construction",
        "landscaping work",
        "tree planting operation",
        "tree trimming blocking road",
        "tree removal operation",
        "stump grinding work",
        "grass cutting near road",
        "hedge trimming work",
        "snow plow operation",
        "salt spreading operation",
        "sand spreading operation",
        "ice removal work",
        "pothole repair",
        "crack sealing work",
        "joint repair work",
        "road marking work",
        "line painting operation",
        "thermoplastic marking application",
        "reflector installation",
        "cat eye installation",
        "speed bump installation",
        "rumble strip installation",
    ],
    
    # ============================================================
    # CATEGORY 6: WEATHER CONDITIONS (50 reasons)
    # ============================================================
    "weather_conditions": [
        "heavy rain reducing visibility",
        "flooding on road",
        "standing water causing slowdown",
        "hydroplaning conditions",
        "thunderstorm causing caution",
        "lightning storm visibility issues",
        "hail storm causing stops",
        "sleet making road slippery",
        "freezing rain conditions",
        "ice on road",
        "black ice conditions",
        "snow accumulation on road",
        "heavy snowfall reducing visibility",
        "blizzard conditions",
        "whiteout conditions",
        "drifting snow blocking lane",
        "avalanche blocking road",
        "fog reducing visibility",
        "dense fog conditions",
        "freezing fog",
        "mist reducing visibility",
        "smoke from fire reducing visibility",
        "dust storm conditions",
        "sandstorm reducing visibility",
        "high winds affecting vehicles",
        "crosswind danger zone",
        "tornado warning causing stops",
        "hurricane evacuation traffic",
        "tropical storm conditions",
        "monsoon flooding",
        "flash flood warning",
        "river overflow onto road",
        "coastal flooding",
        "tidal flooding",
        "water over road",
        "road washout",
        "mudslide blocking road",
        "landslide blocking road",
        "rockslide blocking lane",
        "debris flow on road",
        "falling rocks zone",
        "earthquake damage",
        "road crack from earthquake",
        "bridge damaged by earthquake",
        "sinkhole from rain",
        "heat wave road buckling",
        "extreme heat tire blowouts",
        "sun glare reducing visibility",
        "sunset glare causing caution",
        "sunrise glare affecting drivers",
    ],
    
    # ============================================================
    # CATEGORY 7: DRIVER BEHAVIOR (40 reasons)
    # ============================================================
    "driver_behavior": [
        "frequent braking ahead",
        "sudden braking causing chain reaction",
        "hard braking for obstacle",
        "unnecessary braking",
        "riding brakes downhill",
        "slow acceleration from stop",
        "fast acceleration causing gaps",
        "speed variance between vehicles",
        "slow driver in fast lane",
        "student driver causing slowdown",
        "nervous driver going slowly",
        "elderly driver going slowly",
        "lost driver stopping frequently",
        "rubbernecking at incident",
        "gawking at accident",
        "distracted by billboard",
        "distracted by scenery",
        "taking photos while driving",
        "phone usage while driving",
        "eating while driving",
        "applying makeup while driving",
        "reading while driving",
        "arguing in vehicle",
        "children distraction",
        "pet distraction in vehicle",
        "insect in vehicle causing erratic driving",
        "medical emergency in vehicle",
        "driver fell ill",
        "driver having seizure",
        "driver having heart attack",
        "driver fell asleep",
        "driver under influence",
        "erratic driving behavior",
        "weaving through traffic",
        "lane straddling",
        "failure to maintain lane",
        "improper lane change",
        "cutting off other vehicles",
        "blocking passing lane",
        "refusing to merge",
    ],
    
    # ============================================================
    # CATEGORY 8: VEHICLE TYPES CAUSING DELAYS (30 reasons)
    # ============================================================
    "vehicle_specific": [
        "oversized vehicle on road",
        "wide load transport",
        "overheight vehicle rerouting",
        "overweight vehicle going slowly",
        "agricultural vehicle on road",
        "tractor on road",
        "combine harvester on road",
        "farm equipment moving slowly",
        "construction vehicle on road",
        "excavator transport",
        "crane transport",
        "bulldozer transport",
        "road roller on road",
        "paving machine moving",
        "street sweeper operating",
        "water truck spraying",
        "garbage collection in progress",
        "recycling truck collecting",
        "snow plow in operation",
        "salt truck spreading",
        "military vehicle convoy",
        "tank transport",
        "armored vehicle convoy",
        "ceremonial vehicle procession",
        "vintage car rally",
        "classic car parade",
        "car club convoy",
        "motorcycle group ride",
        "bicycle group ride",
        "organized cycling event",
    ],
    
    # ============================================================
    # CATEGORY 9: SPECIAL EVENTS & SITUATIONS (30 reasons)
    # ============================================================
    "special_situations": [
        "emergency vehicle passing",
        "multiple emergency vehicles responding",
        "police chase in area",
        "high speed pursuit nearby",
        "road closure for dignitary",
        "presidential motorcade",
        "prime minister convoy",
        "royal procession",
        "diplomatic vehicle convoy",
        "military parade",
        "national day parade",
        "independence day celebration",
        "new year celebration crowd",
        "christmas shopping traffic",
        "eid celebration traffic",
        "diwali celebration traffic",
        "chinese new year traffic",
        "thanksgiving travel traffic",
        "memorial day traffic",
        "labor day weekend traffic",
        "school holiday traffic",
        "spring break traffic",
        "summer vacation traffic",
        "winter break traffic",
        "public holiday traffic",
        "bank holiday traffic",
        "long weekend traffic",
        "election day traffic",
        "census counting traffic",
        "emergency evacuation traffic",
    ],
}

# Flatten all reasons into a single list for CLIP
ALL_REASONS = []
for category, reasons in CONGESTION_REASONS.items():
    ALL_REASONS.extend(reasons)

# Get count
TOTAL_REASONS = len(ALL_REASONS)
print(f"Total congestion reasons loaded: {TOTAL_REASONS}")

def get_reasons_by_category(category: str) -> list:
    """Get all reasons for a specific category."""
    return CONGESTION_REASONS.get(category, [])

def get_category_for_reason(reason: str) -> str:
    """Find which category a reason belongs to."""
    for cat, reasons in CONGESTION_REASONS.items():
        if reason in reasons:
            return cat
    return "unknown"

def search_reasons(keyword: str) -> list:
    """Search for reasons containing a keyword."""
    keyword = keyword.lower()
    return [r for r in ALL_REASONS if keyword in r.lower()]
